### ISSUE TITLE
dependency on acorn forces early babel transpilation to avoid erroring

### ISSUE THREAD

**Issue by runspired** [stefanpenner/mr-dep-walk#8]
Since acorn only allows `stage 4` syntax and because this is hard wired to the ES6 setting with no ability to pass in plugins, this means that things which consume mr-dep-walk are held to this constraint unnecessarily unless they transpile all of their code ahead of time.

**Comment by runspired** [comment]
I think we want to use this instead: https://github.com/ternjs/acorn#distacorn_loosejs

**Comment by stefanpenner** [comment]
@runspired 👍

**Comment by runspired** [comment]
@stefanpenner I played with writing a parser that focuses purely on imports and @krisselden has pointed me to the TypeScript preparser for this. Acorn in loose mode doesn't error at all which seems bad if the issue is poorly formatted imports or similar.

**Comment by stefanpenner** [comment]
im down for w/e parser works best here.
